import React from 'react';
import { Download, Users } from 'lucide-react';
import { LineChart, Line, XAxis, YAxis, CartesianGrid, Tooltip, ResponsiveContainer, PieChart, Pie, Cell } from 'recharts';

const ReportsPage = () => {
    // Mock Data for Charts
    const loanTrendData = [
        { name: 'Jul', value: 0 },
        { name: 'Agt', value: 0 },
        { name: 'Sep', value: 0 },
        { name: 'Okt', value: 0 },
        { name: 'Nov', value: 4 }, // Matches the visible slight bump in screenshot
        { name: 'Des', value: 0 },
    ];

    const categoryData = [
        { name: 'Alkitab & Eksegese', value: 20, color: '#eab308' },
        { name: 'Teologi Sistematika', value: 14, color: '#1e293b' },
        { name: 'Umum & Referensi', value: 29, color: '#8b5cf6' },
        { name: 'Pastoral & Konseling', value: 11, color: '#ef4444' },
        { name: 'Pelayanan & Misi', value: 17, color: '#f97316' },
        { name: 'Sejarah Gereja', value: 9, color: '#10b981' },
    ];

    return (
        <div className="p-8">
            <div className="flex items-center justify-between mb-8">
                <div>
                <h2 className="text-2xl font-bold text-slate-800">Laporan Perpustakaan</h2>
                <p className="text-slate-500 text-sm mt-1">Statistik dan analisis data perpustakaan</p>
                </div>
                <button className="px-4 py-2 bg-[#1e293b] text-white rounded-lg text-sm font-medium hover:bg-slate-800 transition-colors flex items-center gap-2 shadow-lg shadow-slate-900/20">
                    <Download size={16} /> Unduh Laporan
                </button>
            </div>

            <div className="grid grid-cols-1 lg:grid-cols-2 gap-8 mb-8">
                {/* Loan Trend Chart */}
                <div className="bg-white p-6 rounded-2xl shadow-sm border border-slate-200">
                    <h3 className="font-bold text-slate-700 mb-6 flex items-center gap-2">
                        <span className="w-1 h-5 bg-amber-500 rounded-full"></span>
                        Tren Peminjaman (6 Bulan Terakhir)
                    </h3>
                    <div className="h-[300px] w-full">
                        <ResponsiveContainer width="100%" height="100%">
                            <LineChart data={loanTrendData}>
                                <CartesianGrid strokeDasharray="3 3" vertical={false} stroke="#e2e8f0" />
                                <XAxis dataKey="name" axisLine={false} tickLine={false} tick={{fill: '#64748b', fontSize: 12}} dy={10} />
                                <YAxis axisLine={false} tickLine={false} tick={{fill: '#64748b', fontSize: 12}} />
                                <Tooltip contentStyle={{ borderRadius: '8px', border: 'none', boxShadow: '0 4px 6px -1px rgb(0 0 0 / 0.1)' }} />
                                <Line type="monotone" dataKey="value" stroke="#eab308" strokeWidth={3} dot={{r: 4, fill: '#eab308', strokeWidth: 2, stroke: '#fff'}} />
                            </LineChart>
                        </ResponsiveContainer>
                    </div>
                </div>

                {/* Category Distribution Chart */}
                <div className="bg-white p-6 rounded-2xl shadow-sm border border-slate-200">
                     <h3 className="font-bold text-slate-700 mb-6 flex items-center gap-2">
                        <span className="w-1 h-5 bg-amber-500 rounded-full"></span>
                        Distribusi Kategori Buku
                    </h3>
                    <div className="h-[300px] w-full relative">
                        <ResponsiveContainer width="100%" height="100%">
                            <PieChart>
                                <Pie
                                    data={categoryData}
                                    cx="50%"
                                    cy="50%"
                                    innerRadius={60}
                                    outerRadius={80}
                                    paddingAngle={5}
                                    dataKey="value"
                                >
                                    {categoryData.map((entry, index) => (
                                        <Cell key={`cell-${index}`} fill={entry.color} />
                                    ))}
                                </Pie>
                                <Tooltip />
                            </PieChart>
                        </ResponsiveContainer>
                        {/* Legend Overlay - positioned absolute to match screenshot layout roughly */}
                        <div className="absolute inset-0 pointer-events-none flex flex-wrap content-center justify-center items-center text-xs text-slate-500 font-medium">
                            {/* In a real app, this legend would be outside or generated by Recharts legend */}
                            {/* Simply simulating the visual density of the donut chart labels from screenshot */}
                        </div>
                        {/* Manual Labels simulation based on screenshot positions approx */}
                         <div className="absolute top-1/2 right-0 transform -translate-y-1/2 text-xs text-slate-500 w-1/3 text-right pr-4">Teologi Sistematika (14%)</div>
                         <div className="absolute top-10 right-10 text-xs text-slate-500">Alkitab & Eksegese (20%)</div>
                         <div className="absolute bottom-10 right-10 text-xs text-slate-500">Umum & Referensi (29%)</div>
                         <div className="absolute bottom-10 left-10 text-xs text-slate-500">Pastoral & Konseling (11%)</div>
                         <div className="absolute top-1/2 left-0 transform -translate-y-1/2 text-xs text-slate-500 w-1/3 text-left pl-4">Pelayanan & Misi (17%)</div>
                         <div className="absolute top-10 left-10 text-xs text-slate-500">Sejarah Gereja (9%)</div>
                    </div>
                </div>
            </div>

            <div className="grid grid-cols-1 lg:grid-cols-2 gap-8">
                 {/* Popular Books List */}
                <div className="bg-white p-6 rounded-2xl shadow-sm border border-slate-200">
                    <h3 className="font-bold text-slate-700 mb-6 flex items-center gap-2">
                        <span className="w-1 h-5 bg-amber-500 rounded-full"></span>
                        Buku Terpopuler
                    </h3>
                    <div className="space-y-4">
                        {[
                        { title: "Teologi Sistematika Volume 1", author: "Louis Berkhof", count: 1 },
                        { title: "Pengantar Perjanjian Lama", author: "Tremper Longman III", count: 1 },
                        { title: "Sejarah Gereja Asia", author: "John C. England", count: 1 },
                        { title: "Misi dan Evangelism", author: "David J. Bosch", count: 0 },
                        { title: "Konseling Pastoral", author: "Gary R. Collins", count: 0 },
                        ].map((book, idx) => (
                        <div key={idx} className="flex items-center gap-4 p-3 hover:bg-slate-50 rounded-xl transition-colors">
                            <div className="w-8 h-8 rounded-lg bg-amber-100 text-amber-600 flex items-center justify-center font-bold text-sm flex-shrink-0">
                                {idx + 1}
                            </div>
                            <div className="flex-1 min-w-0">
                                <h4 className="text-sm font-semibold text-slate-800 truncate">{book.title}</h4>
                                <p className="text-xs text-slate-500 truncate">{book.author}</p>
                            </div>
                            <div className="bg-[#1e293b] text-white text-xs px-2 py-1 rounded-md">
                                {book.count} pinjaman
                            </div>
                        </div>
                        ))}
                    </div>
                </div>

                {/* Active Members List */}
                <div className="bg-white p-6 rounded-2xl shadow-sm border border-slate-200">
                    <h3 className="font-bold text-slate-700 mb-6 flex items-center gap-2">
                        <span className="w-1 h-5 bg-amber-500 rounded-full"></span>
                        Anggota Teraktif
                    </h3>
                     <div className="space-y-4">
                        {[
                             { name: 'Yohanes Mandowen', role: 'Teologi', count: 2, initials: 'YM' },
                             { name: 'Maria Tabuni', role: 'Pendidikan Agama Kristen', count: 1, initials: 'MT' },
                             { name: 'Petrus Wambrauw', role: 'Teologi', count: 0, initials: 'PW' },
                             { name: 'Sarah Kogoya', role: 'Musik Gereja', count: 0, initials: 'SK' },
                        ].map((member, idx) => (
                             <div key={idx} className="flex items-center gap-4 p-3 hover:bg-slate-50 rounded-xl transition-colors">
                                <div className="w-8 h-8 rounded-lg bg-amber-100 text-amber-600 flex items-center justify-center font-bold text-sm flex-shrink-0">
                                    {idx + 1}
                                </div>
                                <div className="w-10 h-10 rounded-full bg-slate-200 flex items-center justify-center text-slate-500 text-xs font-bold">
                                    {member.initials}
                                </div>
                                <div className="flex-1 min-w-0">
                                    <h4 className="text-sm font-semibold text-slate-800 truncate">{member.name}</h4>
                                    <p className="text-xs text-slate-500 truncate">{member.role}</p>
                                </div>
                                 <div className="bg-emerald-50 text-emerald-600 border border-emerald-100 text-xs px-2 py-1 rounded-md">
                                    {member.count} pinjaman
                                </div>
                            </div>
                        ))}
                     </div>
                </div>
            </div>
        </div>
    );
};

export default ReportsPage;